FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*"}

[Project]
Name = "Playground"
StartupObject = "Playground.Main"

[Configs.Release.Win64]
OptimizationLevel = "O3"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Net"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "RecordDomainSynchronizer.bf"
