FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*"}

[Project]
Name = "Playground_Lines"
TargetType = "BeefGUIApplication"
StartupObject = "Playground_Lines.Program"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "ECS"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "FieldDef.bf"
